### ISSUE TITLE
application problems

### ISSUE THREAD

**Issue by LIUJUN-liujun** [martin-pr/possumwood#177]
Dear Martin,
We encountered the following errors when using opengl and polymesh. Is our drive version too high? What version are you using?
Errors as follows:
OpenGL version supported by this platform is 4.6.0 NVIDIA 450.80.02
Segmentation fault (core dumped)
Thanks a lot for your time.

**Comment by martin-pr** [comment]
Hey!

Nope, that is not an error message, just a printout. Can you please give me more details about the problem you've encountered so I can reproduce it? I'd need at least:
- the distro version
- steps to reproduce
- and (preferably) a stack trace from GDB

Thanks a lot!

**Comment by LIUJUN-liujun** [comment]
> Hey!
> Nope, that is not an error message, just a printout. Can you please give me more details about the problem you've encountered so I can reproduce it? I'd need at least:
> 
> the distro version
> steps to reproduce
> and (preferably) a stack trace from GDB
> 
> Also, can I ask what are you using Possumwood for? :) It is still just my personal free-time project, so I am curious if it is getting any use anywhere.
> Thanks a lot!

Hello!
We just can't access opengl and polymesh. When I click on opengl and polymesh, it will display the wrong message. We are using ubuntu20.04, the graphics card is Nvidia RTX2080Ti, and the driver version is 450.80.02. We don't know why opengl and polymesh are not available. We are interested in possumwood because it may be more convenient than other software to process images and 3D models. Hope you can help us solve this problem.
Thanks a lot.

**Comment by martin-pr** [comment]
I really need more details about it - I can't buy the same setup as you have, but with a stacktrace I might be able to find out what is going on.

**Comment by LIUJUN-liujun** [comment]
Hello!
For example, if we click on the sample picture under image, the corresponding picture will appear. But when we click on the examples under opengl and polymesh, it will exit the program directly, showing the problem we mentioned last time. We haven't done any operation of our own, just want to get familiar with the operation of possumwood. We guessed it was a problem with the configuration environment, so we asked the version information to see if it could be resolved. I have sent the video of the operation to your mailbox, and you can see the specific problem I mentioned. Hope you can help us solve it.
Thanks a lot.

**Comment by martin-pr** [comment]
Unfortunately, I am unable to reproduce your problem. The only way forward for me to be able to help you at all is if you send me the stacktrace of the application as it crashes.

**Comment by martin-pr** [comment]
I've added a segfault signal handler and changed the release build to include debugging symbols. If you try to do what you've done triggering the issue, the crash should produce much more information for me to be able to follow up. If you post the result here, I might be able to help.

**Comment by LIUJUN-liujun** [comment]
Thank you for your help.We have tried some solutions recently,but we still can't solve it.Here is the error message:
SIGNAL 11 CAUGHT. This is probably an error in the application. Please create an issue at https://github.com/martin-pr/possumwood/issues, with steps to reproduce and the following stacktrace:
possumwood(_Z13signalHandleri+0x31)[0x55aa12b74a91]
/lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7fd2a15dffd0]
/usr/lib/libpsw_cgal.so(+0x16b80)[0x7fd29b470b80]
/usr/lib/libpsw_cgal.so(+0x1728a)[0x7fd29b47128a]
/usr/lib/libpsw_cgal.so(_ZN10possumwood7loadObjEN5boost10filesystem4pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_SA_+0x38e)[0x7fd29b471aae]
/usr/lib/possumwood/plugins/libcgal.so(+0x1ffdc1)[0x7fd276d5ddc1]
/usr/lib/possumwood/plugins/libcgal.so(_ZNSt17_Function_handlerIFN16dependency_graph5StateERNS0_6ValuesEEPS4_E9_M_invokeERKSt9_Any_dataS3_+0x20)[0x7fd276d19170]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase13computeOutputEm+0xeb)[0x7fd2a3a22d7b]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x6e)[0x7fd2a3a28e7e]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase12computeInputEm+0x5f)[0x7fd2a3a22bff]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x93)[0x7fd2a3a28ea3]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase13computeOutputEm+0xa5)[0x7fd2a3a22d35]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x6e)[0x7fd2a3a28e7e]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase12computeInputEm+0x5f)[0x7fd2a3a22bff]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x93)[0x7fd2a3a28ea3]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase13computeOutputEm+0xa5)[0x7fd2a3a22d35]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x6e)[0x7fd2a3a28e7e]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase12computeInputEm+0x5f)[0x7fd2a3a22bff]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x93)[0x7fd2a3a28ea3]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase13computeOutputEm+0xa5)[0x7fd2a3a22d35]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x6e)[0x7fd2a3a28e7e]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase12computeInputEm+0x5f)[0x7fd2a3a22bff]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x93)[0x7fd2a3a28ea3]
/usr/lib/possumwood/plugins/render.so(+0x365db)[0x7fd29afac5db]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood8Drawable6doDrawERKNS_13ViewportStateE+0x1ad)[0x7fd2a780538d]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood3App4drawERKNS_13ViewportStateESt8functionIFvRKN16dependency_graph8NodeBaseEEE+0x309)[0x7fd2a77dc859]
possumwood(_ZN7Adaptor4drawERKN10possumwood13ViewportStateE+0x61)[0x55aa12b5ef81]
possumwood(_ZN10MainWindow4drawEf+0x20a)[0x55aa12b7ad2a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x865)[0x7fd2a258a555]
possumwood(_ZN8Viewport6renderEf+0x40)[0x55aa12bc2270]
possumwood(_ZN8Viewport7paintGLEv+0x586)[0x55aa12bbc096]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b387d)[0x7fd2a333887d]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1f8)[0x7fd2a3318048]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fd2a32d983c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7fd2a32e1104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7fd2a255b8d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate14sendPaintEventERK7QRegion+0x3a)[0x7fd2a331119a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN13QOpenGLWidget11resizeEventEP12QResizeEvent+0xaa)[0x7fd2a3338cda]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0xda2)[0x7fd2a3318bf2]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fd2a32d983c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7fd2a32e1104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7fd2a255b8d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate15setGeometry_sysEiiiib+0x2d9)[0x7fd2a330ff49]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget11setGeometryERK5QRect+0x80)[0x7fd2a3310cb0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QWidgetItem11setGeometryERK5QRect+0x133)[0x7fd2a32f95b3]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN10QBoxLayout11setGeometryERK5QRect+0x1d0)[0x7fd2a32ef6f0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QLayoutPrivate8doResizeERK5QSize+0x128)[0x7fd2a32f5a88]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x6a)[0x7fd2a32d980a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7fd2a32e1104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7fd2a255b8d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate15setGeometry_sysEiiiib+0x2d9)[0x7fd2a330ff49]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget11setGeometryERK5QRect+0x80)[0x7fd2a3310cb0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x19298f)[0x7fd2a331798f]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget11qt_metacallEN11QMetaObject4CallEiPPv+0x93)[0x7fd2a331a213]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN18QPropertyAnimation18updateCurrentValueERK8QVariant+0x127)[0x7fd2a235a2c7]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x83bf8)[0x7fd2a2354bf8]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x84e2d)[0x7fd2a2355e2d]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN18QPropertyAnimation11updateStateEN18QAbstractAnimation5StateES1_+0x2ea)[0x7fd2a235b3da]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN18QAbstractAnimation5startENS_14DeletionPolicyE+0x1bc)[0x7fd2a2352afc]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x23ec53)[0x7fd2a33c3c53]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x27e900)[0x7fd2a3403900]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2ae300)[0x7fd2a3433300]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2afb4a)[0x7fd2a3434b4a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QMainWindow12restoreStateERK10QByteArrayi+0x123)[0x7fd2a342af43]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood3App8loadFileERKNS_2io10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS1_14adl_serializerEEE+0x4c4)[0x7fd2a77df244]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood3App8loadFileERKNS_8FilepathEb+0x390)[0x7fd2a77dfaa0]
possumwood(_ZN10MainWindow8loadFileERKN5boost10filesystem4pathEb+0x154)[0x55aa12b7daa4]
possumwood(+0x7e616)[0x55aa12b96616]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x97f)[0x7fd2a258a66f]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QAction9triggeredEb+0x42)[0x7fd2a32d3122]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QAction8activateENS_11ActionEventE+0xcc)[0x7fd2a32d580c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x24712b)[0x7fd2a33cc12b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN15QAbstractButton17mouseReleaseEventEP11QMouseEvent+0xfd)[0x7fd2a33cc38d]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QToolButton17mouseReleaseEventEP11QMouseEvent+0xa)[0x7fd2a34ab01a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1f8)[0x7fd2a3318048]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QToolButton5eventEP6QEvent+0x34)[0x7fd2a34ab0b4]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fd2a32d983c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x7ff)[0x7fd2a32e165f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7fd2a255b8d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb+0x1d2)[0x7fd2a32e0632]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1ae16b)[0x7fd2a333316b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b07da)[0x7fd2a33357da]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fd2a32d983c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7fd2a32e1104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7fd2a255b8d8]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x6f3)[0x7fd2a2b1d583]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x135)[0x7fd2a2b1f055]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xab)[0x7fd2a2af62eb]
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x9f260)[0x7fd273d0d260]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2e7)[0x7fd29f342417]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c650)[0x7fd29f342650]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fd29f3426dc]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7fd2a25b488f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x13a)[0x7fd2a255990a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x94)[0x7fd2a25629b4]
possumwood(main+0x6e4)[0x55aa12b5d724]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fd2a15c2b97]
possumwood(_start+0x2a)[0x55aa12b5e2fa]
Thanks a lot for your time.

**Comment by martin-pr** [comment]
Ah, thank you! Yes, your stacktrace is pointing into the .obj loading code. Would you be able to share the file you are loading with me? That would help me to reproduce the issue.

**Comment by LIUJUN-liujun** [comment]
I have sent the object I want to load to your Google mailbox, please receive it. It should be pointed out that I did not load my obj object. I just clicked the opengl example in possumwood, but it did not show the corresponding graphics, but reported an error and exited the program.

**Comment by martin-pr** [comment]
Thank you! I think I found the problem - it should be fixed in current version. Please let me know if it resolved your issue.

**Comment by LIUJUN-liujun** [comment]
Unfortunately,I still can't use it.I have updated it,but there are still problems.At the same time,I found that when doing the same operation, the error code is different every time,I don't know the reason.Here is an error message:
SIGNAL 11 CAUGHT. This is probably an error in the application. Please create an issue at https://github.com/martin-pr/possumwood/issues, with steps to reproduce and the following stacktrace:
possumwood(_Z13signalHandleri+0x31)[0x55ae92db7a91]
/lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f3ddcc4cfd0]
/usr/lib/libpsw_cgal.so(+0x16b80)[0x7f3dd6c70b80]
/usr/lib/libpsw_cgal.so(+0x1728a)[0x7f3dd6c7128a]
/usr/lib/libpsw_cgal.so(_ZN10possumwood7loadObjEN5boost10filesystem4pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_SA_+0x38e)[0x7f3dd6c71aae]
/usr/lib/possumwood/plugins/libcgal.so(+0x1ffdc1)[0x7f3db255ddc1]
/usr/lib/possumwood/plugins/libcgal.so(_ZNSt17_Function_handlerIFN16dependency_graph5StateERNS0_6ValuesEEPS4_E9_M_invokeERKSt9_Any_dataS3_+0x20)[0x7f3db2519170]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase13computeOutputEm+0xeb)[0x7f3ddf08fd7b]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x6e)[0x7f3ddf095e7e]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase12computeInputEm+0x5f)[0x7f3ddf08fbff]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x93)[0x7f3ddf095ea3]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase13computeOutputEm+0xa5)[0x7f3ddf08fd35]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x6e)[0x7f3ddf095e7e]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase12computeInputEm+0x5f)[0x7f3ddf08fbff]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x93)[0x7f3ddf095ea3]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase13computeOutputEm+0xa5)[0x7f3ddf08fd35]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x6e)[0x7f3ddf095e7e]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph8NodeBase12computeInputEm+0x5f)[0x7f3ddf08fbff]
/usr/lib/libdependency_graph.so(_ZN16dependency_graph4Port7getDataEv+0x93)[0x7f3ddf095ea3]
/usr/lib/possumwood/plugins/render.so(+0x365db)[0x7f3dd67ac5db]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood8Drawable6doDrawERKNS_13ViewportStateE+0x1ad)[0x7f3de2e7238d]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood3App4drawERKNS_13ViewportStateESt8functionIFvRKN16dependency_graph8NodeBaseEEE+0x309)[0x7f3de2e49859]
possumwood(_ZN7Adaptor4drawERKN10possumwood13ViewportStateE+0x61)[0x55ae92da1f81]
possumwood(_ZN10MainWindow4drawEf+0x20a)[0x55ae92dbdd2a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x865)[0x7f3dddbf7555]
possumwood(_ZN8Viewport6renderEf+0x40)[0x55ae92e05270]
possumwood(_ZN8Viewport7paintGLEv+0x586)[0x55ae92dff096]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b387d)[0x7f3dde9a587d]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1f8)[0x7f3dde985048]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f3dde94683c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7f3dde94e104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7f3dddbc88d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate14sendPaintEventERK7QRegion+0x3a)[0x7f3dde97e19a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN13QOpenGLWidget11resizeEventEP12QResizeEvent+0xaa)[0x7f3dde9a5cda]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0xda2)[0x7f3dde985bf2]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f3dde94683c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7f3dde94e104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7f3dddbc88d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate15setGeometry_sysEiiiib+0x2d9)[0x7f3dde97cf49]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget11setGeometryERK5QRect+0x80)[0x7f3dde97dcb0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QWidgetItem11setGeometryERK5QRect+0x133)[0x7f3dde9665b3]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN10QBoxLayout11setGeometryERK5QRect+0x1d0)[0x7f3dde95c6f0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QLayoutPrivate8doResizeERK5QSize+0x128)[0x7f3dde962a88]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x6a)[0x7f3dde94680a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7f3dde94e104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7f3dddbc88d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate15setGeometry_sysEiiiib+0x2d9)[0x7f3dde97cf49]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget11setGeometryERK5QRect+0x80)[0x7f3dde97dcb0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x19298f)[0x7f3dde98498f]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget11qt_metacallEN11QMetaObject4CallEiPPv+0x93)[0x7f3dde987213]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN18QPropertyAnimation18updateCurrentValueERK8QVariant+0x127)[0x7f3ddd9c72c7]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x83bf8)[0x7f3ddd9c1bf8]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x84e2d)[0x7f3ddd9c2e2d]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN18QPropertyAnimation11updateStateEN18QAbstractAnimation5StateES1_+0x2ea)[0x7f3ddd9c83da]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN18QAbstractAnimation5startENS_14DeletionPolicyE+0x1bc)[0x7f3ddd9bfafc]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x23ec53)[0x7f3ddea30c53]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x27e900)[0x7f3ddea70900]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2ae300)[0x7f3ddeaa0300]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2afb4a)[0x7f3ddeaa1b4a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QMainWindow12restoreStateERK10QByteArrayi+0x123)[0x7f3ddea97f43]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood3App8loadFileERKNS_2io10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS1_14adl_serializerEEE+0x4c4)[0x7f3de2e4c244]
/usr/lib/libpossumwood_sdk.so(_ZN10possumwood3App8loadFileERKNS_8FilepathEb+0x390)[0x7f3de2e4caa0]
possumwood(_ZN10MainWindow8loadFileERKN5boost10filesystem4pathEb+0x154)[0x55ae92dc0aa4]
possumwood(+0x7e616)[0x55ae92dd9616]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x97f)[0x7f3dddbf766f]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QAction9triggeredEb+0x42)[0x7f3dde940122]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QAction8activateENS_11ActionEventE+0xcc)[0x7f3dde94280c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x24712b)[0x7f3ddea3912b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN15QAbstractButton17mouseReleaseEventEP11QMouseEvent+0xfd)[0x7f3ddea3938d]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QToolButton17mouseReleaseEventEP11QMouseEvent+0xa)[0x7f3ddeb1801a]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1f8)[0x7f3dde985048]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN11QToolButton5eventEP6QEvent+0x34)[0x7f3ddeb180b4]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f3dde94683c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x7ff)[0x7f3dde94e65f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7f3dddbc88d8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb+0x1d2)[0x7f3dde94d632]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1ae16b)[0x7f3dde9a016b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b07da)[0x7f3dde9a27da]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f3dde94683c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x2a4)[0x7f3dde94e104]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x118)[0x7f3dddbc88d8]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x6f3)[0x7f3dde18a583]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x135)[0x7f3dde18c055]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xab)[0x7f3dde1632eb]
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x9f260)[0x7f3daf50d260]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2e7)[0x7f3dda9af417]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c650)[0x7f3dda9af650]
/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f3dda9af6dc]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f3dddc2188f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x13a)[0x7f3dddbc690a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x94)[0x7f3dddbcf9b4]
possumwood(main+0x6e4)[0x55ae92da0724]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f3ddcc2fb97]
possumwood(_start+0x2a)[0x55ae92da12fa]
Looking forward to your help.

**Comment by martin-pr** [comment]
Your message seems to be reporting the same error as last time, but as far as I can see, the valgrind log of this build no longer flags any problem in that particular part of the codebase. 

Please check that your OS updated correctly and that it picked up the latest nighly build of Possumwood - it might not have picked up the latest version - and let me know if the problem persists.

**Comment by LIUJUN-liujun** [comment]
Thanks a lot for your time.We've been able to use it properly.We hope possumwood can do better and better.
